face_0 = ['yellow', 'blue', 'white', 'orange', 'orange', 'yellow', 'red', 'red', 'red']
face_1 = ['blue', 'red', 'green', 'green', 'white', 'red', 'green', 'orange', 'red']
face_2 = ['orange', 'green', 'orange', 'red', 'red', 'orange', 'orange', 'blue', 'blue']
face_3 = ['orange', 'blue', 'blue', 'orange', 'yellow', 'yellow', 'green', 'white', 'blue']
face_4 = ['red', 'green', 'white', 'blue', 'green', 'white', 'yellow', 'yellow', 'white']
face_5 = ['yellow', 'white', 'green', 'green', 'blue', 'yellow', 'white', 'white', 'yellow']
face_input = [face_0, face_1, face_2, face_3, face_4, face_5]